### ISSUE TITLE
Bug in schedule

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/butler-cw#110]
**Describe the bug**
I started butler-cw with parameter "freq: at 11:15 am" in config.
Bug 1 - Warming cache started immediately
Bug 2 - It use UTC time(in logs too), not local (maybe it is feature?)

**To Reproduce**
Use parameter "freq: at 11:15 am" in config

**Expected behavior**
1. Start according to schedule.
2. Use local time(?)

**Describe environment:**
 - OS: Debian 10
 - Containerisation no
 - Version of Butler CW 3.1.1

**Config file(s)**
...
freq: at 11:15 am

**Comment by mountaindude** [comment]
Thx for reporting this. 

I noticed myself that latest version of the scheduler acts funky/not as expected.

Might be that some bug was introduced in that last upgrade. In theory upgrading to latest version of software modules should *remove* bugs, not add new ones... But that's in theory, we're dealing with reality, of course.
Will look into that a bit more. 

Re your bug 1, it's actually normal behaviour. 
I realise it's not really (at all?) documented... but there is a cache warming done for each app when Butler CW is started.
While that's useful at times, it should be configurable.
I've added a new ticket about this: https://github.com/ptarmiganlabs/butler-cw/issues/111

Re bug 2 I am not sure if it's UTC or not.. Will have a look and report back.

**Comment by mountaindude** [comment]
@chevcheli0s 

FYI, I've decided to refactor the entire scheduler part of Butler CW.
First phase (v3.2) will just be an incremental, backwards compatible upgrade. 
Next phase (v4.0) will include breaking changes, but also deliver way more powerful and flexible scheduling (cron schedules, text schedules and more).
