### ISSUE TITLE
Doesn't work on apps with Section Access Enabled

### ISSUE THREAD

**Issue by nitinvishnu** [ptarmiganlabs/butler-cw#20]
This works perfectly on Apps without Section Access. I have few apps where section access in enabled. Can this work on apps enabled with Section Access?

**Comment by levi-turner** [comment]
Two options:
(1) Leave the app alone. Adjust your section access. The program accesses apps using the `sa_repository` user. So add that user to the section access table. Example:

```
section access;
LOAD * inline [
ACCESS, USERID,REDUCTION
ADMIN, QTSEL\LTU,*
USER,QTSEL\SOMEOTHERUSER1,1
USER,QTSEL\SOMEOTHERUSER2,2
USER,EXAMPLE\LICENSEUSER, 3
ADMIN, INTERNAL\SA_SCHEDULER,*
ADMIN, INTERNAL\SA_REPOSITORY,*
];

Section Application;
Data:
LOAD * INLINE [
Customer,Key,Sales
A,1,100
B,2,200
C,3,300
];
```

(2) Adjust the user. In `index.js` the user value is defined as such:
```
            headers: {
                'X-Qlik-User': 'UserDirectory=Internal;UserId=sa_repository'
            },
```
Adjust the `UserId` to some other good value, for example like `sa_scheduler` which already needs to be added to have the app reloaded on a schedule.

**Comment by mountaindude** [comment]
You are quite right about this. 
Unfortunately I cannot see any good way around this. The section access logic is executed during runtime by the Sense engine. Doing cache warming on a section access protected app would require Butler CW to pretend to be all the different users that might use the app (and should have it cached). 

While possible, it's out of scope for Butler CW right now - at least for myself. 
Pull requests are encouraged though! :)
