### ISSUE TITLE
Having an issue 

### ISSUE THREAD

**Issue by RRKONDAVETI** [ptarmiganlabs/butler-cw#7]
Hello,

Receiving follow error, Could you please check it for me

C:\butler-cw-master>node index.js
WARNING: No configurations found in configuration directory:C:\butler-cw-master\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\butler-cw-master\node_modules\config\lib\config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "defaultLogLevel" is not defined
    at Config.get (C:\butler-cw-master\node_modules\config\lib\config.js:203:11)
    at Object.<anonymous> (C:\butler-cw-master\index.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by mountaindude** [comment]
Happy to help, but you need to provide some context. 
The error indicate that Butler can't find its config file.

What does your butler-cw-master directory look like? What files/directories are there?
Have you added a config file with your own config to the config directory?

**Comment by RRKONDAVETI** [comment]
Hi, 

I jsut  followed the instructions.  here is my production.yaml & App_config.yaml
[production.txt](https://github.com/ptarmiganlabs/butler-cw/files/2621705/production.txt)
[apps_config.txt](https://github.com/ptarmiganlabs/butler-cw/files/2621706/apps_config.txt)
![capture](https://user-images.githubusercontent.com/40630446/49109145-e6b31880-f281-11e8-9dab-3bfba1ff87b5.PNG)

**Comment by RRKONDAVETI** [comment]
> Happy to help, but you need to provide some context.
> The error indicate that Butler can't find its config file.
> 
> What does your butler-cw-master directory look like? What files/directories are there?
> Have you added a config file with your own config to the config directory?
Hi Happy new year, Did you get a chance to look at issue
Cheers,
RK

**Comment by RRKONDAVETI** [comment]
Hi Happy new year, Did you get a chance to look at issue
Cheers,
RK

**Comment by nitinvishnu** [comment]
> Hi Happy new year, Did you get a chance to look at issue
> Cheers,
> RK

Did you add the NODE_ENV as environment variable?

**Comment by RRKONDAVETI** [comment]
resolved now.
